services:
  recon:
    build: .
    image: ghcr.io/rocomab/rocom-recon:latest
    container_name: rocom-recon
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      FORCE_PREFIX: "24"
      TOP_PORTS: "200"
      NMAP_TIMING: "T3"
      TARGET_NETWORK: ""
      EXCLUDE_IPS: ""
      ENABLE_MDNS: "true"
      MDNS_SECONDS: "12"
      ENABLE_NETBIOS: "true"
      OUTPUT_DIR: "/output"
    volumes:
      - ./output:/output
    restart: "no"
